import Head from "next/head";
import ProductsPageComp from "../components/productsPageComp";
import { motion as m } from "framer-motion";
import { getProductsData } from "./api/get_productsData";

export default function ProductsPage({ products }) {
  return (
    <>
      <Head>
        <title>Typical Online Store - Products</title>
        <meta name="online store" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <m.main
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5, ease: "easeInOut" }}
        exit={{ opacity: 0 }}
        className="font-latoRegular"
      >
        <section>
          <div className="text-center text-2xl text-teal-500">
            <p>THIS IS CURRENTLY ONLY FOR FRONT-END, NO DATABASES YET</p>
            <p>
              THE TOTAL ON THE NAVBAR WILL NOT UPDATE BECAUSE IT IS NOT SAVED
              ANYWHERE :(
            </p>
          </div>
        </section>
        <ProductsPageComp products={products} />
      </m.main>
    </>
  );
}

export const getServerSideProps = async () => {
  const productsData = await getProductsData();

  return {
    props: {
      products: productsData,
    },
  };
};
