import Head from "next/head";
import NavBar from "../components/navbar";
import HomePage from "../components/homePage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Typical Online Store</title>
        <meta name="online store" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <HomePage />
      </div>
    </div>
  );
}
