import Head from "next/head";
import HomePage from "../components/homePage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Typical E-commerce - Home</title>
        <meta name="online store" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  );
}
