import LoginPage from "../components/loginPage";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Typical E-commerce - Login</title>
        <meta name="online store" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginPage />
    </div>
  );
}
