import Head from "next/head";
import ProductsPageComp from "../components/productsPageComp";

export default function ProductsPage() {
  return (
    <>
      <Head>
        <title>Typical Online Store - Products</title>
        <meta name="online store" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <div className="text-center text-2xl text-teal-500">
            <p>THIS IS CURRENTLY ONLY FOR FRONT-END, NO DATABASES YET</p>
            <p>
              THE TOTAL ON THE NAVBAR WILL NOT UPDATE BECAUSE IT IS NOT SAVED
              ANYWHERE
            </p>
            <p>
              HOWEVER THE ONE MADE DIRECTLY CONNECTED TO THE COMPONENT BELOW
              WORKS
            </p>
            <p>
              Also finding images one by one is hard, decided to just make it
              myself with <span className="text-pink-600">very high </span>
              effort ;)
            </p>
          </div>
        </section>
        <ProductsPageComp />
      </main>
    </>
  );
}
