import Head from "next/head";
import ProductsPage from "../components/productsPage";

export default function Products() {
  return (
    <div>
      <Head>
        <title>Typical Online Store</title>
        <meta name="online store" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ProductsPage />
      </div>
    </div>
  );
}
