import Head from "next/head";
import { motion as m } from "framer-motion";

import CartComp from "../components/cartComp/cartComp";
import { cartHandler } from "./api/cartHandler";
import { globalHandler } from "./api/globalHandler";

export default function HomePage({ cart }) {
  return (
    <>
      <Head>
        <title>Typical Online Store - Home</title>
        <meta name="online store" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <m.main
        key={"key1"}
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5, ease: "easeInOut" }}
        exit={{ opacity: 0 }}
        className="font-latoRegular"
      >
        <CartComp cart={cart} />
      </m.main>
    </>
  );
}

export const getServerSideProps = async () => {
  const globalValues = await globalHandler("GET");
  const currentUserId = globalValues.loggedUserId;

  const cartData = await cartHandler("GET", "", undefined, currentUserId);

  return {
    props: {
      cart: cartData,
    },
  };
};
