import Head from "next/head";
import Link from "next/link";
import { useFormik } from "formik";
import * as Yup from "yup";
import { useRouter } from "next/router";
import { motion as m } from "framer-motion";

export default function LoginPage() {
  const router = useRouter();

  // formik
  const formik = useFormik({
    initialValues: {
      email: "",
      password: "",
    },

    validationSchema: Yup.object({
      email: Yup.string()
        .email("Invalid email address")
        .required("Email is required"),
      password: Yup.string()
        .min(8, "Password must be 8 characters or more")
        .max(20, "Let's be real here, you don't even remember this")
        .required("Password is required"),
    }),

    onSubmit: (values) => {
      console.log(values);
      router.push({ pathname: "/success", query: values });
    },
  });

  return (
    <>
      <Head>
        <title>Typical Online Store - Login</title>
        <meta name="online store" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <m.main
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5, ease: "easeIn" }}
        exit={{ opacity: 0 }}
        className="w-full"
      >
        <div className="flex items-center justify-center min-h-screen">
          <form
            onSubmit={formik.handleSubmit}
            className="bg-white flex rounded-lg font-latoRegular max-w-md"
          >
            <div className="flex-1 text-gray-700 p-14 w-screen">
              <h1 className="text-3xl pb-2 font-latoBold">Log In</h1>
              <p className="font-latoLight">
                Not a proper user authentication because json-server cannot deal
                with nested array in database, so it will just detect the user
                id to know which user logged in, cart content will remain the
                same
              </p>
              <div className="mt-6">
                {/* Email input field */}
                <div className="pb-4">
                  <label
                    className="block font-latoBold text-sm pb-2"
                    htmlFor="email"
                  >
                    Email
                  </label>
                  <input
                    className="border-2 border-gray-500 p-2 rounded-md w-full focus:border-emerald-500 focus:ring-emerald-500"
                    type="email"
                    name="email"
                    placeholder="Enter your email"
                    value={formik.values.email}
                    onChange={formik.handleChange}
                    onBlur={formik.handleBlur}
                  ></input>
                  <p className="block font-latoBold text-sm pt-2 text-red-500">
                    {formik.touched.email && formik.errors.email
                      ? formik.errors.email
                      : ""}
                  </p>
                </div>

                {/* Password input field */}
                <div className="pb-4">
                  <label
                    className="block font-latoBold text-sm pb-2"
                    htmlFor="password"
                  >
                    Password
                  </label>
                  <input
                    className="border-2 border-gray-500 p-2 rounded-md w-full focus:border-emerald-500 focus:ring-emerald-500"
                    type="password"
                    name="password"
                    placeholder="Enter your password"
                    value={formik.values.password}
                    onChange={formik.handleChange}
                    onBlur={formik.handleBlur}
                  ></input>
                  <p className="block font-latoBold text-sm pt-2 text-red-500">
                    {formik.touched.password && formik.errors.password
                      ? formik.errors.password
                      : ""}
                  </p>
                </div>
                <button
                  type="submit"
                  className="bg-emerald-500 font-latoBold text-sm text-white py-3 my-6 rounded-lg w-full hover:bg-purple-500"
                >
                  Log In
                </button>
              </div>
              <p className="font-latoLight text-gray-500 break-normal text-center">
                Need an Account?{" "}
                <Link
                  href="/register"
                  className="text-emerald-500 underline font-bold hover:text-purple-500"
                >
                  Create a new one
                </Link>
              </p>
            </div>
          </form>
        </div>
      </m.main>
    </>
  );
}
