import Head from "next/head";
import { motion as m } from "framer-motion";
import { productHandler } from "./api/productHandler";

import ProductsComp from "../components/productsComp/productsComp";

export default function ProductsPage({ products }) {
  return (
    <>
      <Head>
        <title>Typical Online Store - Products</title>
        <meta name="online store" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <m.main
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5, ease: "easeInOut" }}
        exit={{ opacity: 0 }}
        className="font-latoRegular"
      >
        <ProductsComp products={products} />
      </m.main>
    </>
  );
}

export const getServerSideProps = async () => {
  const productsData = await productHandler("GET");

  return {
    props: {
      products: productsData,
    },
  };
};
