import Head from "next/head";
import Link from "next/link";

import { AiOutlineArrowLeft } from "react-icons/ai";
import { motion as m } from "framer-motion";
import { productHandler } from "./api/productHandler";
import ViewProductComp from "../components/viewProductComp/viewProductComp";

export default function ProductsPage({ product }) {
  return (
    <>
      <Head>
        <title>Typical Online Store - Products</title>
        <meta name="online store" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <m.main
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5, ease: "easeInOut" }}
        exit={{ opacity: 0 }}
        className="font-latoRegular min-h-screen"
      >
        <span className="flex">
          <Link
            href="/products"
            className="ml-10 mt-4 flex flex-wrap items-center bg-teal-500 hover:bg-teal-400 text-white text-lg font-bold py-2 px-4 border-b-4 border-teal-700 hover:border-teal-500 rounded md:ml-24 lg:ml-10 2xl:ml-48"
          >
            <AiOutlineArrowLeft className="text-2xl" />
            Return
          </Link>
        </span>
        <ViewProductComp product={product} />
      </m.main>
    </>
  );
}

export const getServerSideProps = async (ctx) => {
  const { query } = ctx;
  // prevents user to go to this page without the router data
  // also this if statement checks if query is empty or not
  if (Object.keys(query).length === 0 || query.id === undefined) {
    return {
      redirect: {
        destination: "/products",
        permanent: false,
      },
    };
  } else {
    const productData = await productHandler("GET", "None", query.id);
    return {
      props: {
        product: productData,
      },
    };
  }
};
