import Head from "next/head";

import { motion as m } from "framer-motion";
import { productHandler } from "./api/productHandler";
import ViewProductComp from "../components/viewProductComp/viewProductComp";

export default function ViewProductPage({ product }) {
  return (
    <>
      <Head>
        <title>Typical Online Store - Products - {product.name}</title>
        <meta name="online store" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <m.main
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5, ease: "easeInOut" }}
        exit={{ opacity: 0 }}
        className="font-latoRegular min-h-screen"
      >
        <ViewProductComp product={product} />
      </m.main>
    </>
  );
}

export const getServerSideProps = async (ctx) => {
  const { query } = ctx;
  // prevents user to go to this page without the router data
  // also this if statement checks if query is empty or not
  if (Object.keys(query).length === 0 || query.id === undefined) {
    return {
      redirect: {
        destination: "/products",
        permanent: false,
      },
    };
  } else {
    const productData = await productHandler("GET", "None", query.id);
    return {
      props: {
        product: productData,
      },
    };
  }
};
